/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package address_book;


import dbconnection1.DbConnection1;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Validations.Validations;



public class View_Entries extends javax.swing.JFrame {

    /**
     * Creates new form addressBook
     */
    public View_Entries() {
        initComponents();
        table_update();
    }
      
     boolean b= false;
   int row;
    
//      Boolean b=false;
      ArrayList<String> al;
    HashMap<Integer, ArrayList> hm= new HashMap<>();
      DefaultTableModel dtm;
    int sr_no= 0;
    File file;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Address", "City", "State", "Zip", "Phoneno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Back");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Email Id");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("City");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("State");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Zip");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Phone_No");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Andra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujrat", "Haryana", "Himanchal Pradesh", "Jammu And Kashmir", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttarakhand", "Uttar Pradesh", "West Bengal", "Andaman And Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli", "Daman And Diu", "Delhi", "Lakshadweep", "Puducherry" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton5.setText("Sort By Name");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Sort By Zip");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mac-address-book.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(31, 31, 31)
                        .addComponent(jButton5)
                        .addGap(33, 33, 33)
                        .addComponent(jButton6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)
                                    .addComponent(jComboBox1, 0, 193, Short.MAX_VALUE)
                                    .addComponent(jTextField5)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(72, 72, 72)
                                .addComponent(jTextField1)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 21, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
      int c;
    public void table_update()
    {
        
        try( Connection con= DbConnection1.getConnect();
                PreparedStatement ps= con.prepareStatement("select * from insert_value ");
                ResultSet rs= ps.executeQuery();
               
                )
        {
             ResultSetMetaData rss= rs.getMetaData();
             c= rss.getColumnCount();
             
            DefaultTableModel dtm= (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            
             
            while(rs.next())
            {
                
                Vector v2= new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString(1));
                    v2.add(rs.getString(2));
                    v2.add(rs.getString(3));
                    v2.add(rs.getString(4));
                    v2.add(rs.getString(5));
                    v2.add(rs.getString(6));
                    v2.add(rs.getString(7));
                }
                
                dtm.addRow(v2);
                
                
                
            }
                
                
                
        }
         catch(SQLException e)
        {
    
        }        
    }
    
    
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        DefaultTableModel dtm= (DefaultTableModel)jTable1.getModel();
//          
//           String name, first_name, last_name, phoneno, email, gender, address, city;
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         dtm = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        
       
         int zipid= Integer.parseInt(dtm.getValueAt(row, 5).toString());
//         System.out.println(zipid);
        String name1= jTextField1.getText();
        String email1= jTextField2.getText();
        String address1= jTextArea1.getText();
        String city1= jTextField3.getText();
        String state1= (String)jComboBox1.getSelectedItem();
        int zip1= Integer.valueOf(jTextField4.getText());
        String phoneno1= jTextField5.getText();
        String query = "update insert_value set name= '"+name1+"', email= '"+email1+"', address= '"+address1+"', city= '"+city1+"', state= '"+state1+"', phoneno= '"+phoneno1+"' where zip= '"+String.valueOf(zipid)+"'  ";
        try
        {
        Connection con= DbConnection1.getConnect();
                PreparedStatement ps= con.prepareStatement(query);

//               ps.setString(0, name1);
//               ps.setString(1, email1);
//               ps.setString(2, address1);
//               ps.setString(3, city1);
//               ps.setString(4, state1);
//               ps.setString(5, phoneno1);
//               ps.setInt(6, zipid);
               
               
               int i= ps.executeUpdate();
               if(i>0)
               {
                   JOptionPane.showMessageDialog(rootPane, "User Updated Successfully ");
                    table_update();
                   
                   
                   jTextField1.setText("");
                   jTextField2.setText("");
                   jTextArea1.setText("");
                   jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                   
                  
                  
               }
               else
               {
                   JOptionPane.showMessageDialog(rootPane, "User cannot be Updated", "Error", JOptionPane.ERROR_MESSAGE );
                    jTextField1.setText("");
                   jTextField2.setText("");
                   jTextArea1.setText("");
                   jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                   
                   
                   
               }
                
                
        
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

      
    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        al= new ArrayList<>();
        String name1= jTextField1.getText();
        String email1= jTextField2.getText();
        String address1= jTextArea1.getText();
        String city1= jTextField3.getText();
        String state1= (String)jComboBox1.getSelectedItem();
        int zip1= Integer.valueOf(jTextField4.getText());
        String phoneno1= jTextField5.getText();
        
        String aa[]= {name1, email1, address1, city1, state1, String.valueOf(zip1), phoneno1};
        
          Validations v= new Validations();
            v.nameValidate(name1);
            
            if(!v.nameValidate(name1))
            {
                JOptionPane.showMessageDialog(rootPane, "Name must only contains small and capital letters", "Error", JOptionPane.ERROR_MESSAGE);
            }
           
             else if(!v.emailValidate(email1))
            {
                  JOptionPane.showMessageDialog(rootPane, "Email is not valid", "Error", JOptionPane.ERROR_MESSAGE );
            }
             
             else if(b)
             {
                 JOptionPane.showMessageDialog(rootPane, "Email already Exist");
             }
             
              else if(!v.addressValidate(address1))
            {
                 JOptionPane.showMessageDialog(rootPane, "Address is not valid" , "Error", JOptionPane.ERROR_MESSAGE);
            }
              else if(!v.cityValidate(city1))
            {
                 JOptionPane.showMessageDialog(rootPane, "City is not valid" , "Error", JOptionPane.ERROR_MESSAGE);
            }
              else if(!v.zipValidate(String.valueOf(zip1)))
            {
                 JOptionPane.showMessageDialog(rootPane, "Zip is not valid" , "Error", JOptionPane.ERROR_MESSAGE);
            } 
              
                
              else if(!v.phonenoValidate(phoneno1))
            {
                 JOptionPane.showMessageDialog(rootPane, "Phone Number is not Valid", "Error", JOptionPane.ERROR_MESSAGE);
            }
               
             else{
        
               try(Connection con= DbConnection1.getConnect();
                    PreparedStatement ps= con.prepareStatement("insert into insert_value values(?, ?, ?, ?, ?, ?, ?)");
                  )
               {
               
               
               ps.setString(1, name1);
               ps.setString(2, email1);
               ps.setString(3, address1);
               ps.setString(4, city1);
               ps.setString(5, state1);
               ps.setInt(6, zip1);
               ps.setString(7, phoneno1);
               
               
               int i= ps.executeUpdate();
               if(i>0)
               {
                   JOptionPane.showMessageDialog(rootPane, "User Added Successfully ");
                    table_update();
                   
                   jTextField1.setText("");
                   jTextField2.setText("");
                   jTextArea1.setText("");
                   jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                   
                  
                  
               }
               else
               {
                   JOptionPane.showMessageDialog(rootPane, "User cannot be added", "Error", JOptionPane.ERROR_MESSAGE );
                    jTextField1.setText("");
                   jTextField2.setText("");
                   jTextArea1.setText("");
                   jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                   
                   
                   
               }
               
               
           }
           catch(Exception e)
           {
             e.printStackTrace();
               
           }
           
           }
        
        
        
        
        
        
        
        
        
        
        
    
        
        try(FileOutputStream fos=new FileOutputStream("f://'"+name1+"'.txt"))
        {
//          
              
//            byte[][] b= aa.getBytes();
           
                       byte[][] b = new byte[aa.length][];
                       for (int i=0;  i<b.length;  i++) {
                       b[i]= aa[i].getBytes();


                 fos.write(b[i]);
                  }
        }
         catch(IOException e)
        {
            e.printStackTrace();
        }
        

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered

    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        Address_Book1 ab= new Address_Book1();
       ab.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

         dtm = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        jTextField1.setText(dtm.getValueAt(row, 0).toString());
         jTextField2.setText(dtm.getValueAt(row, 1).toString());
        jTextArea1.setText(dtm.getValueAt(row, 2).toString());
        jTextField3.setText(dtm.getValueAt(row, 3).toString());
        try
        {
            jComboBox1.setSelectedIndex(Integer.parseInt(dtm.getValueAt(row, 4).toString()));
        }
        catch(NumberFormatException ee)
        {
            
        }
        
        jTextField4.setText(dtm.getValueAt(row, 5).toString());
        jTextField5.setText(dtm.getValueAt(row, 6).toString());
        setEnabled(true);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         
         dtm = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        
       
         int zipid= Integer.parseInt(dtm.getValueAt(row, 5).toString());
//         System.out.println(zipid);
        String name1= jTextField1.getText();
        String email1= jTextField2.getText();
        String address1= jTextArea1.getText();
        String city1= jTextField3.getText();
        String state1= (String)jComboBox1.getSelectedItem();
        String phoneno1= jTextField5.getText();
        String query = " DELETE from insert_value where zip= '"+String.valueOf(zipid)+"' ";
        try
        {
        Connection con= DbConnection1.getConnect();
                PreparedStatement ps= con.prepareStatement(query);

      int i= ps.executeUpdate();
               if(i>0)
               {
                   JOptionPane.showMessageDialog(rootPane, "User Deleted Successfully ");
                    table_update();
                   
                   
                   jTextField1.setText("");
                   jTextField2.setText("");
                   jTextArea1.setText("");
                   jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                   
                  
                  
               }
               else
               {
                   JOptionPane.showMessageDialog(rootPane, "User Deletion Failed ", "Error", JOptionPane.ERROR_MESSAGE );
                    jTextField1.setText("");
                   jTextField2.setText("");
                   jTextArea1.setText("");
                   jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                   
                   
                   
               }
                
                
        
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
          
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         dtm = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        
//        String zip1= jTextField4.getText();
//         int zipid= Integer.parseInt(dtm.getValueAt(row, 5).toString());
      
        String query = "select * from insert_value order by name asc";
          
         try( Connection con= DbConnection1.getConnect();
                PreparedStatement ps= con.prepareStatement(query);
                ResultSet rs= ps.executeQuery();
               
                )
        {
             ResultSetMetaData rss= rs.getMetaData();
             c= rss.getColumnCount();
             
            DefaultTableModel dtm= (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            
             
            while(rs.next())
            {
                
                Vector v2= new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString(1));
                    v2.add(rs.getString(2));
                    v2.add(rs.getString(3));
                    v2.add(rs.getString(4));
                    v2.add(rs.getString(5));
                    v2.add(rs.getString(6));
                    v2.add(rs.getString(7));
                }
                
                dtm.addRow(v2);
                
                
                
            }
                
                
                
        }
         catch(SQLException e)
        {
    
        }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          dtm = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        
//        String zip1= jTextField4.getText();
//         int zipid= Integer.parseInt(dtm.getValueAt(row, 5).toString());
      
        String query = "select * from insert_value order by zip asc";
          
         try( Connection con= DbConnection1.getConnect();
                PreparedStatement ps= con.prepareStatement(query);
                ResultSet rs= ps.executeQuery();
               
                )
        {
             ResultSetMetaData rss= rs.getMetaData();
             c= rss.getColumnCount();
             
            DefaultTableModel dtm= (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            
             
            while(rs.next())
            {
                
                Vector v2= new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString(1));
                    v2.add(rs.getString(2));
                    v2.add(rs.getString(3));
                    v2.add(rs.getString(4));
                    v2.add(rs.getString(5));
                    v2.add(rs.getString(6));
                    v2.add(rs.getString(7));
                }
                
                dtm.addRow(v2);
                
                
                
            }
                
                
                
        }
         catch(SQLException e)
        {
    
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Entries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
